### ISSUE TITLE
Fail to capture 400 status code

### ISSUE THREAD

**Issue by taka-yayoi** [elsevierlabs-os/NotebookDiscovery#1]
Thank you for very useful notebooks!

I encountered the following error during indexing:

`HTTP request failed with status: 400 {“error”:“DatabricksServiceException: BAD_REQUEST: content size...`

Then looking into the your code, I found the following logic in NotebookIndex Cmd 13 (getDBRestResponse).

`
 } else if (statusCode == 400 && content.contains("{\"error\":\"DatabricksServiceException: BAD_REQUEST: content size (14025371) exceeded the limit 10485760\"}")) {
`

But that criterion includes contents size number 14025371, so **contains** does not work.

It's better to relax the criterion as follows:

`} else if (statusCode == 400 && content.contains("{\"error\":\"DatabricksServiceException: BAD_REQUEST")) {`

**Comment by dmcbeath** [comment]
Thank you for identifying this error.  I will plan to get this fixed later today and push an update.

**Comment by dmcbeath** [comment]
This issue has been closed.  The fix is contained in NotebookDiscovery-1.0.1.dbc.
