### ISSUE TITLE
Add excludePatterns parameter

### ISSUE THREAD

**Issue by ssimeonov** [elsevierlabs-os/NotebookDiscovery#4]
This is a great tool. Thank you for open-sourcing it.

Using the tool would become easier if there is a way to optionally exclude some notebooks using pattern-based rules.

The simplest implementation, albeit not the most user friendly, would be to use a single regular expression. Using anchoring and disjunction (`|`) many separate patterns can be handled via a single regex. A more user-friendly way would be to support a list of glob patterns.

**Comment by dmcbeath** [comment]
Thanks Simeon.  Glad you find the tool useful.    I should have some time in the next few weeks to investigate adding the exclude functionality.    I will keep you updated.

**Comment by dmcbeath** [comment]
Support has been added to exclude notebooks via the optional specification of a comma separated list of globs as an excludes parameter in NotebookIndexRun.  This requires NotebookDiscovery 1.0.4.  Let me know if you experience any problems with using this capability.  Thank you for your patience.
